global:
  scrape_interval: 15s

scrape_configs:
  - job_name: ride-backend
    static_configs:
      - targets:
          - ride-backend:8080
  - job_name: ride-signaling
    static_configs:
      - targets:
          - ride-signaling:8081
